[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src 'self'"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), camera=(), microphone=()"
